services:
  - type: web
    name: app  # or whatever you want to call the service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
